<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class WorkSeeder extends Seeder
{
    public function run()
    {
        //Array de obras con sus datos
        $works = [
            [
                'name' => 'A Chambra Branca',
                'artist' => 'Seoane',
                'type' => 'Pintura',
                'image' => '/images/works/A-Chambra-Branca.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'A Ría',
                'artist' => 'Nacho Costa',
                'type' => 'Pintura',
                'image' => '/images/works/A-Ria.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Abismo I',
                'artist' => 'Antón Pulido',
                'type' => 'Pintura',
                'image' => '/images/works/Abismo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Anónimo',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Anonimo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Arlequín',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/Arlequin.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Barcos Al Atardecer',
                'artist' => 'Eloy Hernández',
                'type' => 'Pintura',
                'image' => '/images/works/Barcos.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Bisonte',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Bisonte.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Borracho',
                'artist' => 'Carlos Alcolea',
                'type' => 'Pintura',
                'image' => '/images/works/Borracho.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Cajas',
                'artist' => 'Ánxel Huete',
                'type' => 'Pintura',
                'image' => '/images/works/Cajas.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Camiño Vermello',
                'artist' => 'Antón Pulido',
                'type' => 'Pintura',
                'image' => '/images/works/Camiño-Vermello.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Chatarra',
                'artist' => 'Aramburu',
                'type' => 'Pintura',
                'image' => '/images/works/Chatarra.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Ciclistas',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/Ciclistas.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Composición Abstracta1',
                'artist' => 'Deside',
                'type' => 'Pintura',
                'image' => '/images/works/Composicion-Abstracta.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Composición Abstracta2',
                'artist' => 'Deside',
                'type' => 'Pintura',
                'image' => '/images/works/Composicion.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Contemplando La Batalla',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Contemplando-La-Batalla.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Desafío',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Desafio.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Deconstrucción',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Deconstruccion.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Durmindo Nas Olas',
                'artist' => 'Antón Pulido',
                'type' => 'Pintura',
                'image' => '/images/works/Durmindo-Nas-Olas.png',
                'price' => '3490,99€',
            ],
            [
                'name' => 'El Peregrino',
                'artist' => 'Lugrís Vadillo',
                'type' => 'Pintura',
                'image' => '/images/works/El-Peregrino.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Entropía',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Entropia.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Escrita Das Árbores',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/Escrita-Das-Arbores.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Espazo Ingrávido',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/Espazo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Espello De Papel',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Espello-de-Papel.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'A Mar Espello',
                'artist' => 'Antón Sobral',
                'type' => 'Pintura',
                'image' => '/images/works/Espello.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Familia Americana',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/Familia.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Felino',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Felino.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Fósiles',
                'artist' => 'Sandra Carvalho',
                'type' => 'Pintura',
                'image' => '/images/works/Fosiles.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Hibernáculo',
                'artist' => 'Jorge Barbi',
                'type' => 'Escultura',
                'image' => '/images/works/Hibernaculo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Hierros',
                'artist' => 'Aramburu',
                'type' => 'Pintura',
                'image' => '/images/works/Hierros.jpeg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Historia',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Historia.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Interea',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Interea.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Islas Cíes',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Islas-cies.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'La Palmera',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/La-Palmera.png',
                'price' => '3490,99€',
            ],
            [
                'name' => 'La Sagrada Familia',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/La-Sagrada-Familia.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Levitando',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Levitando.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Loco Por Los Libros',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Loco.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Maternidad',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Maternidad.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Maternidad2',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Maternidade.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Mesa Quebrada',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/Mesa.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Muller III',
                'artist' => 'Antón Pulido',
                'type' => 'Pintura',
                'image' => '/images/works/Muller.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Nas Marxes',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/Nas-Marxes.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'New York',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/New-York.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título1',
                'artist' => 'Jorge Barbi',
                'type' => 'Escultura',
                'image' => '/images/works/no.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título2',
                'artist' => 'Carlos Alcolea',
                'type' => 'Pintura',
                'image' => '/images/works/notitulo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Serie Océano',
                'artist' => 'Antón Sobral',
                'type' => 'Pintura',
                'image' => '/images/works/oceano.png',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Pagina N2',
                'artist' => 'Antonio Murado',
                'type' => 'Pintura',
                'image' => '/images/works/Pagina.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Paisaje Arenoso',
                'artist' => 'Antonio Murado',
                'type' => 'Pintura',
                'image' => '/images/works/Paisaje-Arenoso.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Pájaros Sobre Hojas',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/Pajaros.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Papelería Compostela',
                'artist' => 'Mar Hernández',
                'type' => 'Pintura',
                'image' => '/images/works/Papeleria.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Papeles Encontrados',
                'artist' => 'Sandra Carvalho',
                'type' => 'Pintura',
                'image' => '/images/works/Papeles.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Perdices',
                'artist' => 'Antón Lamazares',
                'type' => 'Pintura',
                'image' => '/images/works/Perdices.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Personajes Y Aves',
                'artist' => 'Jorge Castillo',
                'type' => 'Pintura',
                'image' => '/images/works/Personajes.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Personaxes De Millet',
                'artist' => 'Salveiro Rivas',
                'type' => 'Escultura',
                'image' => '/images/works/Personaxes-De-Millet.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Pesanervios',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/Pesanervios.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Paternidad',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Petenidad.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Piscina B',
                'artist' => 'Carlos Alcolea',
                'type' => 'Pintura',
                'image' => '/images/works/PiscinaB.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Puesta De Sol',
                'artist' => 'Antón Sobral',
                'type' => 'Pintura',
                'image' => '/images/works/Puesta.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Recorrido',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/Recorrido.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sello 23',
                'artist' => 'Antón Lamazares',
                'type' => 'Pintura',
                'image' => '/images/works/Sellos.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título3',
                'artist' => 'Silveiro Rivas',
                'type' => 'Escultura',
                'image' => '/images/works/Sin.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título4',
                'artist' => 'Jorge Barbi',
                'type' => 'Escultura',
                'image' => '/images/works/sin1.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título5',
                'artist' => 'Jorge Barbi',
                'type' => 'Escultura',
                'image' => '/images/works/sin2.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título6',
                'artist' => 'Jorge Barbi',
                'type' => 'Escultura',
                'image' => '/images/works/sin3.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sin Título7',
                'artist' => 'Alfonso Costa',
                'type' => 'Pintura',
                'image' => '/images/works/sintituo.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Soledad',
                'artist' => 'Ramón Conde',
                'type' => 'Escultura',
                'image' => '/images/works/Soledad.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'ST',
                'artist' => 'Antón Patiño',
                'type' => 'Pintura',
                'image' => '/images/works/ST.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'st',
                'artist' => 'Pilar Alonso',
                'type' => 'Pintura',
                'image' => '/images/works/st.png',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Sufrido',
                'artist' => 'Antón Lamazares',
                'type' => 'Pintura',
                'image' => '/images/works/Sufrido.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Suplementos',
                'artist' => 'Sandra Carvalho',
                'type' => 'Pintura',
                'image' => '/images/works/Suplemento.jpg',
                'price' => '3490,99€',
            ],
            [
                'name' => 'Venecia',
                'artist' => 'Antón Sobral',
                'type' => 'Pintura',
                'image' => '/images/works/Venecia.jpg',
                'price' => '3490,99€',
            ],
        ];
        //Insertamos las obras en la base de datos
        foreach ($works as $work) {
            $this->db->table('works')->insert($work);
        }
    }
}
